[tool.poetry]
name = 'py-leap'
version = '0.1a16'
packages = [{include = 'leap', from='src'}]
description = ''
authors = ['Guillermo Rodriguez <guillermo@telos.net>']
readme = 'README.md'

[tool.poetry.dependencies]
python = '>=3.8'
asks = '^3.0.0'
base58 = '^2.1.1'
cryptos = '^2.0.9'
natsort = '^8.4.0'
requests = '^2.31.0'
msgspec = '0.18.4'
pdbplus = '^1.5.0'

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = {version = '^7.4.2'}

[tool.poetry.group.nodemngr]
optional = true

[tool.poetry.group.nodemngr.dependencies]
bs4 = {version = '^0.0.1'}
docker = {version = '^6.1.3'}
zstandard = {version = '^0.21.0'}

[tool.pytest.ini_options]
log_cli = true
log_cli_level = 'INFO'
markers = [
    'bootstrap: test requires full chain bootstrap',
    'contracts: specify contracts you need deployed'
]

[build-system]
requires = ['poetry-core']
build-backend = 'poetry.core.masonry.api'
